"""Composition-test cases (data), generated from the retired test.yaml."""

CASES = [{'name': 'basic',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'}}}},
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'Network',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'region': 'eastus',
                                                        'addressRange': '10.224.0.0/16',
                                                        'generalSubnetRange': '10.224.0.0/24'}}},
                               {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'AKS',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'region': 'eastus',
                                                        'version': '1.34',
                                                        'nodes': {'count': 2,
                                                                  'instanceType': 'Standard_D2s_v3'}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'forProvider': {'chart': {'version': '2.2.1-up.1'},
                                                         'values': {'upbound': {'manager': {'metering': {'podSecurityContext': {'fsGroup': 65532,
                                                                                                                                'fsGroupChangePolicy': 'OnRootMismatch'}}}}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-certmanager'},
                                'spec': {'forProvider': {'chart': {'name': 'cert-manager',
                                                                   'repository': 'https://charts.jetstack.io',
                                                                   'version': 'v1.20.3'},
                                                         'namespace': 'cert-manager'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-release-aks'},
                                'spec': {'of': {'kind': 'AKS'}, 'by': {'kind': 'Release'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-aks-network'},
                                'spec': {'of': {'kind': 'Network'}, 'by': {'kind': 'AKS'}}}]}},
 {'name': 'network-custom',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'westeurope',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'network': {'addressRange': '172.20.0.0/16',
                                                      'generalSubnetRange': '172.20.1.0/24'}}}},
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'Network',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'region': 'westeurope',
                                                        'addressRange': '172.20.0.0/16',
                                                        'generalSubnetRange': '172.20.1.0/24'}}}]}},
 {'name': 'backup-enabled',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001/uxp-backups'}}}},
           'assertResources': [{'apiVersion': 'storage.azure.m.upbound.io/v1beta1',
                                'kind': 'Account',
                                'metadata': {'name': 'mybackup001'},
                                'spec': {'forProvider': {'location': 'eastus'},
                                         'providerConfigRef': {'name': 'default',
                                                               'kind': 'ProviderConfig'}}},
                               {'apiVersion': 'storage.azure.m.upbound.io/v1beta1',
                                'kind': 'Container',
                                'metadata': {'name': 'test-cp-backup-container'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-config'},
                                'spec': {'forProvider': {'manifest': {'spec': {'objectStorage': {'provider': 'Azure',
                                                                                                 'credentials': {'source': 'InjectedIdentity'}}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-rbac'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-rbac-binding'}}]}},
 {'name': 'backup-cross-region',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001/uxp-backups',
                                                     'bucketRegion': 'westus2'}}}},
           'assertResources': [{'apiVersion': 'storage.azure.m.upbound.io/v1beta1',
                                'kind': 'Account',
                                'metadata': {'name': 'mybackup001'},
                                'spec': {'forProvider': {'location': 'westus2'}}},
                               {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'Network',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'region': 'eastus'}}}]}},
 {'name': 'with-license',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001/uxp-backups'},
                                          'license': {'secretRef': {'name': 'uxp-license',
                                                                    'namespace': 'default'}}}}},
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-uxp-license-secret'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-uxp-license'},
                                'spec': {'forProvider': {'manifest': {'kind': 'License'}}}}]}},
 {'name': 'no-backup',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'}}}},
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'Network',
                                'metadata': {'name': 'test-cp'}},
                               {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'AKS',
                                'metadata': {'name': 'test-cp'}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'}}]}},
 {'name': 'with-schedule',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001/uxp-backups',
                                                     'schedule': '@daily'}}}},
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-config'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-schedule'},
                                'spec': {'forProvider': {'manifest': {'kind': 'BackupSchedule',
                                                                      'spec': {'schedule': '@daily',
                                                                               'configRef': {'name': 'test-cp-backup'}}}}}}]}},
 {'name': 'with-vpa',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'providerVerticalPodAutoscaling': {'enabled': 'yes',
                                                                             'minCpu': '500m',
                                                                             'maxCpu': '2',
                                                                             'minMemory': '100Mi',
                                                                             'maxMemory': '4000Mi'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-vpa'},
                                'spec': {'forProvider': {'chart': {'name': 'vpa',
                                                                   'repository': 'https://charts.fairwinds.com/stable',
                                                                   'version': '4.10.1'},
                                                         'namespace': 'kube-system'}}}]}},
 {'name': 'with-vpa-deployed',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'providerVerticalPodAutoscaling': {'enabled': 'yes',
                                                                             'minCpu': '500m',
                                                                             'maxCpu': '2',
                                                                             'minMemory': '100Mi',
                                                                             'maxMemory': '4000Mi'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-vpa',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'vpa-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'vpa',
                                                                     'repository': 'https://charts.fairwinds.com/stable',
                                                                     'version': '4.10.1'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-upbound-runtime-config'},
                                'spec': {'forProvider': {'manifest': {'kind': 'UpboundRuntimeConfig',
                                                                      'spec': {'capabilities': ['ProviderVPA']}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'forProvider': {'values': {'upbound': {'manager': {'args': ['--enable-provider-vpa']}}}}}}]}},
 {'name': 'backup-uxp-deployed',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001/uxp-backups'}}}},
           'observedResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                  'kind': 'AKS',
                                  'metadata': {'name': 'test-cp',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'aks'}},
                                  'status': {'aks': {'oidcUrl': 'https://eastus.oic.prod-aks.azure.com/00000000-0000-0000-0000-000000000000/abcdef/',
                                                     'clusterName': 'test-cp-aks',
                                                     'nodes': {'vmSize': 'Standard_D2s_v3'}}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-uxp',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'uxp-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'crossplane',
                                                                     'repository': 'oci://xpkg.upbound.io/upbound',
                                                                     'version': '2.2.1-up.1'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'managedidentity.azure.m.upbound.io/v1beta1',
                                'kind': 'UserAssignedIdentity',
                                'metadata': {'name': 'test-cp-backup-identity'},
                                'spec': {'providerConfigRef': {'name': 'default',
                                                               'kind': 'ProviderConfig'}}},
                               {'apiVersion': 'managedidentity.azure.m.upbound.io/v1beta1',
                                'kind': 'FederatedIdentityCredential',
                                'metadata': {'name': 'test-cp-backup-federation'},
                                'spec': {'forProvider': {'issuer': 'https://eastus.oic.prod-aks.azure.com/00000000-0000-0000-0000-000000000000/abcdef/',
                                                         'subject': 'system:serviceaccount:crossplane-system:upbound-controller-manager'}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-sa'},
                                'spec': {'forProvider': {'manifest': {'kind': 'ServiceAccount',
                                                                      'metadata': {'name': 'upbound-controller-manager',
                                                                                   'namespace': 'crossplane-system'}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-controller-restart'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Deployment',
                                                                      'metadata': {'name': 'upbound-controller-manager',
                                                                                   'namespace': 'crossplane-system'}}}}}]}},
 {'name': 'uxp-targets-crossplane-system',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'forProvider': {'namespace': 'crossplane-system',
                                                         'chart': {'name': 'crossplane'}}}}]}},
 {'name': 'vpa-and-knative-merged',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'providerVerticalPodAutoscaling': {'enabled': 'yes'},
                                          'knative': {'enabled': 'yes'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-vpa',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'vpa-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'vpa',
                                                                     'repository': 'https://charts.fairwinds.com/stable',
                                                                     'version': '4.10.1'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-certmanager',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'certmanager-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'cert-manager',
                                                                     'repository': 'https://charts.jetstack.io',
                                                                     'version': 'v1.20.3'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-knative-operator',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'knative-operator-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'knative-operator',
                                                                     'repository': 'https://knative.github.io/operator',
                                                                     'version': 'v1.21.1'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                  'kind': 'Object',
                                  'metadata': {'name': 'test-cp-knative-serving-cr',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'knative-serving-cr'}},
                                  'spec': {'providerConfigRef': {'name': 'test-cp'}},
                                  'status': {'atProvider': {'manifest': {'status': {'conditions': [{'type': 'Ready',
                                                                                                    'status': 'True'}]}}}}}],
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-upbound-runtime-config'},
                                'spec': {'forProvider': {'manifest': {'spec': {'capabilities': ['ProviderVPA',
                                                                                                'FunctionKnativeRuntime']}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'forProvider': {'values': {'upbound': {'manager': {'args': ['--enable-provider-vpa',
                                                                                                     '--enable-knative-runtime']}}}}}}]}},
 {'name': 'with-knative',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'knative': {'enabled': 'yes'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-certmanager'},
                                'spec': {'forProvider': {'chart': {'name': 'cert-manager',
                                                                   'repository': 'https://charts.jetstack.io'}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-knative-operator'},
                                'spec': {'forProvider': {'chart': {'name': 'knative-operator',
                                                                   'repository': 'https://knative.github.io/operator'}}}}]}},
 {'name': 'with-install-from',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D4s_v3'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'newcpbackup/uxp-backups',
                                                     'installFrom': {'location': 'oldcpbackup/uxp-backups',
                                                                     'name': 'old-cp-backup-002'}}}}},
           'assertResources': [{'apiVersion': 'storage.azure.m.upbound.io/v1beta1',
                                'kind': 'Account',
                                'metadata': {'name': 'newcpbackup'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-config'},
                                'spec': {'forProvider': {'manifest': {'spec': {'objectStorage': {'bucket': 'uxp-backups',
                                                                                                 'config': {'storage_account': 'newcpbackup'}}}}}}}]}},
 {'name': 'availability-zones',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.35',
                                          'nodes': {'count': 3,
                                                    'vmSize': 'Standard_D2s_v3',
                                                    'availabilityZones': ['1', '2', '3']}}}},
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'AKS',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'region': 'eastus',
                                                        'version': '1.35',
                                                        'nodes': {'count': 3,
                                                                  'instanceType': 'Standard_D2s_v3',
                                                                  'availabilityZones': ['1',
                                                                                        '2',
                                                                                        '3']}}}}]}},
 {'name': 'vm-size-drift',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'}}}},
           'observedResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                  'kind': 'AKS',
                                  'metadata': {'name': 'test-cp',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'aks'}},
                                  'status': {'aks': {'clusterName': 'test-cp-aks',
                                                     'nodes': {'vmSize': 'Standard_D4s_v3'}}}}],
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'AKS',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'nodes': {'instanceType': 'Standard_D2s_v3'}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'}},
                               {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'ControlPlane',
                                'metadata': {'name': 'test-cp'},
                                'status': {'controlplane': {'clusterName': 'test-cp-aks',
                                                            'nodes': {'currentVmSize': 'Standard_D4s_v3'}}}}]}},
 {'name': 'with-envoy-gateway',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'argocd': {'enabled': 'yes'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-envoy-gateway',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'envoy-gateway-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-envoy-gateway'},
                                'spec': {'forProvider': {'chart': {'name': 'gateway-helm',
                                                                   'repository': 'oci://docker.io/envoyproxy',
                                                                   'version': 'v1.8.2'},
                                                         'namespace': 'envoy-gateway-system'}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-envoy-proxy-config'},
                                'spec': {'forProvider': {'manifest': {'kind': 'EnvoyProxy',
                                                                      'spec': {'provider': {'type': 'Kubernetes',
                                                                                            'kubernetes': {'envoyService': {'type': 'LoadBalancer'}}}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-gateway-class'},
                                'spec': {'forProvider': {'manifest': {'kind': 'GatewayClass',
                                                                      'spec': {'controllerName': 'gateway.envoyproxy.io/gatewayclass-controller',
                                                                               'parametersRef': {'group': 'gateway.envoyproxy.io',
                                                                                                 'kind': 'EnvoyProxy',
                                                                                                 'name': 'eg-proxy',
                                                                                                 'namespace': 'envoy-gateway-system'}}}}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-envoy-gateway-aks'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-envoy-proxy-config-aks'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-gateway-class-aks'}}]}},
 {'name': 'with-k8gb',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'observedResources': [{'apiVersion': 'network.azure.m.upbound.io/v1beta1',
                                  'kind': 'PublicIP',
                                  'metadata': {'name': 'test-cp-k8gb-ip',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-ip'}},
                                  'status': {'atProvider': {'ipAddress': '20.1.2.3',
                                                            'id': '/subscriptions/x/resourceGroups/test-cp-rg/providers/Microsoft.Network/publicIPAddresses/test-cp-k8gb-ip'}}}],
           'assertResources': [{'apiVersion': 'network.azure.m.upbound.io/v1beta1',
                                'kind': 'PublicIP',
                                'metadata': {'name': 'test-cp-k8gb-ip'},
                                'spec': {'forProvider': {'sku': 'Standard',
                                                         'allocationMethod': 'Static',
                                                         'location': 'eastus',
                                                         'resourceGroupNameSelector': {'matchLabels': {'azure.platform.upbound.io/network-id': 'test-cp'}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-k8gb',
                                             'annotations': {'crossplane.io/external-name': 'k8gb'}},
                                'spec': {'forProvider': {'chart': {'name': 'k8gb',
                                                                   'repository': 'https://www.k8gb.io',
                                                                   'version': 'v0.20.0'},
                                                         'namespace': 'k8gb',
                                                         'values': {'k8gb': {'clusterGeoTag': 'azure-eastus-test-cp',
                                                                             'installLegacyCrds': True,
                                                                             'dnsZones': [{'loadBalancedZone': 'gslb.example.com',
                                                                                           'parentZone': 'example.com'}]},
                                                                    'extdns': {'enabled': False},
                                                                    'coredns': {'serviceType': 'LoadBalancer',
                                                                                'servers': [{'zones': [{'zone': '.',
                                                                                                        'use_tcp': False}],
                                                                                             'port': 5353,
                                                                                             'servicePort': 53,
                                                                                             'plugins': [{'name': 'prometheus',
                                                                                                          'parameters': '0.0.0.0:9153'}]}],
                                                                                'service': {'annotations': {'service.beta.kubernetes.io/azure-pip-name': 'test-cp-k8gb-ip',
                                                                                                            'service.beta.kubernetes.io/azure-load-balancer-resource-group': 'test-cp-rg'}}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-k8gb-coredns'},
                                'spec': {'managementPolicies': ['Observe'],
                                         'forProvider': {'manifest': {'kind': 'Service',
                                                                      'metadata': {'name': 'k8gb-coredns',
                                                                                   'namespace': 'k8gb'}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-envoy-gateway'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-k8gb-aks'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-k8gb-coredns-aks'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-k8gb-ip-release'}},
                               {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'ControlPlane',
                                'metadata': {'name': 'test-cp'},
                                'status': {'controlplane': {'k8gb': {'enabled': 'yes',
                                                                     'nsName': 'gslb-ns-azure-eastus-test-cp-gslb.example.com'}}}}]}},
 {'name': 'with-k8gb-endpoint',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'observedResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                  'kind': 'Object',
                                  'metadata': {'name': 'test-cp-k8gb-coredns',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-coredns-observe'}},
                                  'status': {'atProvider': {'manifest': {'status': {'loadBalancer': {'ingress': [{'ip': '20.9.9.9'}]}}}}}},
                                 {'apiVersion': 'network.azure.m.upbound.io/v1beta1',
                                  'kind': 'PublicIP',
                                  'metadata': {'name': 'test-cp-k8gb-ip',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-ip'}},
                                  'status': {'atProvider': {'ipAddress': '20.9.9.9',
                                                            'id': '/subscriptions/x/resourceGroups/test-cp-rg/providers/Microsoft.Network/publicIPAddresses/test-cp-k8gb-ip'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-k8gb',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'ControlPlane',
                                'metadata': {'name': 'test-cp'},
                                'status': {'controlplane': {'k8gb': {'enabled': 'yes',
                                                                     'coreDNSEndpoint': '20.9.9.9',
                                                                     'nsName': 'gslb-ns-azure-eastus-test-cp-gslb.example.com',
                                                                     'glueAddresses': ['20.9.9.9'],
                                                                     'delegationRecord': 'gslb.example.com. '
                                                                                         '30 IN NS '
                                                                                         'gslb-ns-azure-eastus-test-cp-gslb.example.com.\n'
                                                                                         'gslb-ns-azure-eastus-test-cp-gslb.example.com. '
                                                                                         '30 IN A '
                                                                                         '20.9.9.9'}}}}]}},
 {'name': 'with-argocd',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'argocd': {'enabled': 'yes',
                                                     'hostname': 'argocd.example.com',
                                                     'url': 'https://github.com/example/apps'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-argocd',
                                             'annotations': {'crossplane.io/external-name': 'argocd'}},
                                'spec': {'forProvider': {'chart': {'name': 'argo-cd',
                                                                   'repository': 'https://argoproj.github.io/argo-helm'},
                                                         'namespace': 'argocd',
                                                         'values': {'configs': {'params': {'server.insecure': True}}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-envoy-gateway'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-argocd-aks'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-argocd-gateway-aks'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-argocd-httproute-aks'}}]}},
 {'name': 'with-argocd-deployed',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'argocd': {'enabled': 'yes',
                                                     'hostname': 'argocd.example.com',
                                                     'url': 'https://github.com/example/apps'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-certmanager',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'certmanager-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-argocd',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'argocd-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-envoy-gateway',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'envoy-gateway-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-issuer'},
                                'spec': {'forProvider': {'manifest': {'kind': 'ClusterIssuer',
                                                                      'metadata': {'name': 'argocd-selfsigned'}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-cert'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Certificate',
                                                                      'spec': {'secretName': 'argocd-server-tls',
                                                                               'issuerRef': {'name': 'argocd-selfsigned',
                                                                                             'kind': 'ClusterIssuer'}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-app'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Application',
                                                                      'spec': {'source': {'repoURL': 'https://github.com/example/apps',
                                                                                          'path': '.',
                                                                                          'targetRevision': 'HEAD'}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-gateway'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Gateway',
                                                                      'spec': {'gatewayClassName': 'eg',
                                                                               'listeners': [{'name': 'https',
                                                                                              'protocol': 'HTTPS',
                                                                                              'port': 443,
                                                                                              'hostname': 'argocd.example.com',
                                                                                              'tls': {'mode': 'Terminate',
                                                                                                      'certificateRefs': [{'name': 'argocd-server-tls'}]}}]}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-httproute'},
                                'spec': {'forProvider': {'manifest': {'kind': 'HTTPRoute',
                                                                      'spec': {'parentRefs': [{'name': 'argocd',
                                                                                               'sectionName': 'https'}],
                                                                               'hostnames': ['argocd.example.com'],
                                                                               'rules': [{'backendRefs': [{'name': 'argocd-server',
                                                                                                           'port': 80}]}]}}}}}]}},
 {'name': 'management-mode-provision',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'managementMode': 'Provision',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'AKS',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'managementPolicies': ['Observe',
                                                                               'Create',
                                                                               'Update',
                                                                               'LateInitialize']}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'managementPolicies': ['Observe',
                                                                'Create',
                                                                'Update',
                                                                'LateInitialize']}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-certmanager'},
                                'spec': {'managementPolicies': ['Observe',
                                                                'Create',
                                                                'Update',
                                                                'LateInitialize']}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-k8gb-coredns'},
                                'spec': {'managementPolicies': ['Observe']}}]}},
 {'name': 'management-mode-observeonly',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'managementMode': 'ObserveOnly',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'}}}},
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'AKS',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'managementPolicies': ['Observe']}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'managementPolicies': ['Observe']}}]}},
 {'name': 'management-mode-deprovision',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'managementMode': 'Deprovision',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'AKS',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'managementPolicies': ['Create',
                                                                               'Delete',
                                                                               'Observe']}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'managementPolicies': ['Create', 'Delete', 'Observe']}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-k8gb-coredns'},
                                'spec': {'managementPolicies': ['Observe']}}]}},
 {'name': 'namespaced-core',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'}}}},
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'Network',
                                'metadata': {'name': 'test-cp', 'namespace': 'platform'}},
                               {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'AKS',
                                'metadata': {'name': 'test-cp', 'namespace': 'platform'}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp', 'namespace': 'platform'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-aks-network',
                                             'namespace': 'platform'},
                                'spec': {'of': {'kind': 'Network',
                                                'resourceRef': {'name': 'test-cp',
                                                                'namespace': 'platform'}}}}]}},
 {'name': 'default-namespace-fallback',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'default'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'}}}},
           'assertResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'AKS',
                                'metadata': {'name': 'test-cp', 'namespace': 'default'}}]}},
 {'name': 'namespaced-backup',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001/uxp-backups'}}}},
           'observedResources': [{'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                  'kind': 'AKS',
                                  'metadata': {'name': 'test-cp',
                                               'namespace': 'platform',
                                               'annotations': {'crossplane.io/composition-resource-name': 'aks'}},
                                  'status': {'aks': {'oidcUrl': 'https://eastus.oic.prod-aks.azure.com/00000000-0000-0000-0000-000000000000/abcdef/',
                                                     'clusterName': 'test-cp-aks',
                                                     'nodes': {'vmSize': 'Standard_D2s_v3'}}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-uxp',
                                               'namespace': 'platform',
                                               'annotations': {'crossplane.io/composition-resource-name': 'uxp-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'crossplane',
                                                                     'repository': 'oci://xpkg.upbound.io/upbound',
                                                                     'version': '2.2.1-up.1'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'storage.azure.m.upbound.io/v1beta1',
                                'kind': 'Account',
                                'metadata': {'name': 'mybackup001', 'namespace': 'platform'},
                                'spec': {'forProvider': {'location': 'eastus'},
                                         'providerConfigRef': {'name': 'default',
                                                               'kind': 'ProviderConfig'}}},
                               {'apiVersion': 'storage.azure.m.upbound.io/v1beta1',
                                'kind': 'Container',
                                'metadata': {'name': 'test-cp-backup-container',
                                             'namespace': 'platform'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-config',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'manifest': {'spec': {'objectStorage': {'provider': 'Azure',
                                                                                                 'credentials': {'source': 'InjectedIdentity'}}}}}}},
                               {'apiVersion': 'managedidentity.azure.m.upbound.io/v1beta1',
                                'kind': 'UserAssignedIdentity',
                                'metadata': {'name': 'test-cp-backup-identity',
                                             'namespace': 'platform'},
                                'spec': {'providerConfigRef': {'name': 'default',
                                                               'kind': 'ProviderConfig'}}},
                               {'apiVersion': 'managedidentity.azure.m.upbound.io/v1beta1',
                                'kind': 'FederatedIdentityCredential',
                                'metadata': {'name': 'test-cp-backup-federation',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'issuer': 'https://eastus.oic.prod-aks.azure.com/00000000-0000-0000-0000-000000000000/abcdef/',
                                                         'subject': 'system:serviceaccount:crossplane-system:upbound-controller-manager'}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-sa', 'namespace': 'platform'},
                                'spec': {'forProvider': {'manifest': {'kind': 'ServiceAccount',
                                                                      'metadata': {'name': 'upbound-controller-manager',
                                                                                   'namespace': 'crossplane-system'}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-controller-restart',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Deployment',
                                                                      'metadata': {'name': 'upbound-controller-manager',
                                                                                   'namespace': 'crossplane-system'}}}}}]}},
 {'name': 'namespaced-k8gb',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'observedResources': [{'apiVersion': 'network.azure.m.upbound.io/v1beta1',
                                  'kind': 'PublicIP',
                                  'metadata': {'name': 'test-cp-k8gb-ip',
                                               'namespace': 'platform',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-ip'}},
                                  'status': {'atProvider': {'ipAddress': '20.1.2.3',
                                                            'id': '/subscriptions/x/resourceGroups/test-cp-rg/providers/Microsoft.Network/publicIPAddresses/test-cp-k8gb-ip'}}}],
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-k8gb',
                                             'namespace': 'platform',
                                             'annotations': {'crossplane.io/external-name': 'k8gb'}},
                                'spec': {'forProvider': {'chart': {'name': 'k8gb',
                                                                   'repository': 'https://www.k8gb.io',
                                                                   'version': 'v0.20.0'},
                                                         'namespace': 'k8gb',
                                                         'values': {'k8gb': {'clusterGeoTag': 'azure-eastus-test-cp',
                                                                             'installLegacyCrds': True,
                                                                             'dnsZones': [{'loadBalancedZone': 'gslb.example.com',
                                                                                           'parentZone': 'example.com'}]},
                                                                    'extdns': {'enabled': False},
                                                                    'coredns': {'serviceType': 'LoadBalancer',
                                                                                'servers': [{'zones': [{'zone': '.',
                                                                                                        'use_tcp': False}],
                                                                                             'port': 5353,
                                                                                             'servicePort': 53,
                                                                                             'plugins': [{'name': 'prometheus',
                                                                                                          'parameters': '0.0.0.0:9153'}]}]}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-k8gb-coredns',
                                             'namespace': 'platform'},
                                'spec': {'managementPolicies': ['Observe'],
                                         'forProvider': {'manifest': {'kind': 'Service',
                                                                      'metadata': {'name': 'k8gb-coredns',
                                                                                   'namespace': 'k8gb'}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-envoy-gateway',
                                             'namespace': 'platform'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-k8gb-aks',
                                             'namespace': 'platform'},
                                'spec': {'of': {'kind': 'AKS',
                                                'resourceRef': {'name': 'test-cp',
                                                                'namespace': 'platform'}}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-k8gb-coredns-aks',
                                             'namespace': 'platform'},
                                'spec': {'of': {'kind': 'AKS',
                                                'resourceRef': {'name': 'test-cp',
                                                                'namespace': 'platform'}}}}]}},
 {'name': 'namespaced-argocd',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'argocd': {'enabled': 'yes',
                                                     'hostname': 'argocd.example.com',
                                                     'url': 'https://github.com/example/apps'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-argocd',
                                             'namespace': 'platform',
                                             'annotations': {'crossplane.io/external-name': 'argocd'}},
                                'spec': {'forProvider': {'chart': {'name': 'argo-cd',
                                                                   'repository': 'https://argoproj.github.io/argo-helm'},
                                                         'namespace': 'argocd',
                                                         'values': {'configs': {'params': {'server.insecure': True}}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-envoy-gateway',
                                             'namespace': 'platform'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-argocd-aks',
                                             'namespace': 'platform'},
                                'spec': {'of': {'kind': 'AKS',
                                                'resourceRef': {'name': 'test-cp',
                                                                'namespace': 'platform'}}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-argocd-gateway-aks',
                                             'namespace': 'platform'},
                                'spec': {'of': {'kind': 'AKS',
                                                'resourceRef': {'name': 'test-cp',
                                                                'namespace': 'platform'}}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-argocd-httproute-aks',
                                             'namespace': 'platform'},
                                'spec': {'of': {'kind': 'AKS',
                                                'resourceRef': {'name': 'test-cp',
                                                                'namespace': 'platform'}}}}]}},
 {'name': 'namespaced-vpa',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'providerVerticalPodAutoscaling': {'enabled': 'yes',
                                                                             'minCpu': '500m',
                                                                             'maxCpu': '2',
                                                                             'minMemory': '100Mi',
                                                                             'maxMemory': '4000Mi'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-vpa', 'namespace': 'platform'},
                                'spec': {'forProvider': {'chart': {'name': 'vpa',
                                                                   'repository': 'https://charts.fairwinds.com/stable',
                                                                   'version': '4.10.1'},
                                                         'namespace': 'kube-system'}}}]}},
 {'name': 'with-k8gb-ip-pending',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'assertResources': [{'apiVersion': 'network.azure.m.upbound.io/v1beta1',
                                'kind': 'PublicIP',
                                'metadata': {'name': 'test-cp-k8gb-ip'}},
                               {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                'kind': 'ControlPlane',
                                'metadata': {'name': 'test-cp'},
                                '(status.controlplane.k8gb.glueAddresses == null)': True,
                                '(status.controlplane.k8gb.delegationRecord == null)': True}]}},
 {'name': 'with-k8gb-ip-role',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'eastus',
                                          'version': '1.34',
                                          'nodes': {'count': 2, 'vmSize': 'Standard_D2s_v3'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'observedResources': [{'apiVersion': 'network.azure.m.upbound.io/v1beta1',
                                  'kind': 'PublicIP',
                                  'metadata': {'name': 'test-cp-k8gb-ip',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-ip'}},
                                  'status': {'atProvider': {'ipAddress': '20.1.2.3',
                                                            'id': '/subscriptions/x/resourceGroups/test-cp-rg/providers/Microsoft.Network/publicIPAddresses/test-cp-k8gb-ip'}}},
                                 {'apiVersion': 'azure.platform.upbound.io/v1alpha1',
                                  'kind': 'AKS',
                                  'metadata': {'name': 'test-cp',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'aks'}},
                                  'status': {'aks': {'identityPrincipalId': '11111111-2222-3333-4444-555555555555'}}}],
           'assertResources': [{'apiVersion': 'authorization.azure.m.upbound.io/v1beta1',
                                'kind': 'RoleAssignment',
                                'metadata': {'name': 'test-cp-k8gb-ip-role'},
                                'spec': {'forProvider': {'principalId': '11111111-2222-3333-4444-555555555555',
                                                         'principalType': 'ServicePrincipal',
                                                         'skipServicePrincipalAadCheck': True,
                                                         'roleDefinitionName': 'Network '
                                                                               'Contributor',
                                                         'scope': '/subscriptions/x/resourceGroups/test-cp-rg'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-k8gb-ip-role-release'}}]}}]
